apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service  # Give your service a name
spec:
  type: LoadBalancer  # This will create an external IP
  ports:
    - port: 80        # The port that the service will expose
      targetPort: 8080 # The port your Flask app is running on
  selector:
    app: simple-flask  # This should match the labels in your deployment
